/// Flutter icons FoodIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FoodIcon
///      fonts:
///       - asset: fonts/FoodIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class FoodIcons {
  FoodIcons._();

  static const String _kFontFam = 'FoodIcons';

  static const IconData wheat = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData milk = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cheese = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData diet = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData salad = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData meat = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData fork = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData cupcake = IconData(0xe808, fontFamily: _kFontFam);
}
